server:
  port: 5000
  servlet:
    contextPath: /api

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Buenos_Aires
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      jdbc:
        time_zone: America/Argentina/Buenos_Aires
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
deploy:
  artifact: target/demo-0.0.1-SNAPSHOT.jar